project_name: goldmark-lint

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/goldmark-lint
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

kos:
  - repository: ghcr.io/mrueg/goldmark-lint
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
