version: 2

project_name: goldmark-lint

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/goldmark-lint
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

kos:
  - repositories:
      - ghcr.io/mrueg/goldmark-lint
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64

brews:
  - repository:
      owner: mrueg
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/mrueg/goldmark-lint"
    description: "A Markdown linter written in Go using the goldmark parser"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
